// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PGHub.DataAccess;

namespace PGHub.Migrations
{
    [DbContext(typeof(PostgreSqlContext))]
    partial class PostgreSqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PGHub.Entity.Payment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("code")
                        .HasColumnType("text");

                    b.Property<string>("key")
                        .HasColumnType("text");

                    b.Property<string>("merchant_id")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("prefix")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("PGHub.Entity.Transaction", b =>
                {
                    b.Property<string>("trx_id")
                        .HasColumnType("text");

                    b.Property<string>("bill_currency")
                        .HasColumnType("text");

                    b.Property<string>("bill_date")
                        .HasColumnType("text");

                    b.Property<string>("bill_desc")
                        .HasColumnType("text");

                    b.Property<string>("bill_expired")
                        .HasColumnType("text");

                    b.Property<string>("bill_no")
                        .HasColumnType("text");

                    b.Property<string>("bill_total")
                        .HasColumnType("text");

                    b.Property<string>("cust_name")
                        .HasColumnType("text");

                    b.Property<string>("cust_no")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("merchant_id")
                        .HasColumnType("text");

                    b.Property<string>("msisdn")
                        .HasColumnType("text");

                    b.Property<string>("pay_type")
                        .HasColumnType("text");

                    b.Property<string>("payment_channel")
                        .HasColumnType("text");

                    b.Property<string>("payment_channel_uid")
                        .HasColumnType("text");

                    b.Property<string>("payment_date")
                        .HasColumnType("text");

                    b.Property<string>("payment_reff")
                        .HasColumnType("text");

                    b.Property<string>("payment_status_code")
                        .HasColumnType("text");

                    b.Property<string>("payment_status_desc")
                        .HasColumnType("text");

                    b.Property<string>("payment_total")
                        .HasColumnType("text");

                    b.Property<string>("signature")
                        .HasColumnType("text");

                    b.Property<string>("terminal")
                        .HasColumnType("text");

                    b.Property<string>("va_number")
                        .HasColumnType("text");

                    b.HasKey("trx_id");

                    b.ToTable("transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
